# Generated by Django 6.0.1 on 2026-03-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("time_spent", models.FloatField()),
                ("concept_links", models.FloatField()),
                ("knowledge_gaps", models.FloatField()),
                ("research_questions", models.FloatField()),
                ("learning_efficiency", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
